#!/bin/bash
#
# Makefile generator for Problems
#
MAKEFILE=Makefile

CFLAGS="-Wall -Wpedantic --std=c99"
CPPFLAGS="-Wall -Wpedantic --std=c++11"

CFILES=$(ls *.c)
CPPFILES=$(ls *.cpp)

BINDIR="bin"

PROGS=
for file in $CFILES;  do
    PROGS="$PROGS $(basename $file .c)"
done
for file in $CPPFILES;  do
    PROGS="$PROGS $(basename $file .cpp)"
done

if [ -e $MAKEFILE ]; then
    rm -f $MAKEFILE
fi

echo "# Generated Makefile for Problems" > $MAKEFILE
echo "" >> $MAKEFILE
echo "BIN = $BINDIR" >> $MAKEFILE
echo "" >> $MAKEFILE
echo "all:$PROGS" >> $MAKEFILE
echo "" >> $MAKEFILE
echo "$BINDIR:" >> $MAKEFILE
echo "	mkdir -p $BINDIR" >> $MAKEFILE
echo "" >> $MAKEFILE

for file in $CPPFILES; do
    prog=$(basename $file .cpp)
    echo "$prog: $file | $BINDIR" >> $MAKEFILE
    echo "	g++ $CPPFLAGS -o \$(BIN)/$prog $file -lm" >> $MAKEFILE
    echo "" >> $MAKEFILE
done

for file in $CFILES; do
    prog=$(basename $file .c)
    echo "$prog: $file | $BINDIR" >> $MAKEFILE
    echo "	gcc $CFLAGS -o \$(BIN)/$prog $file -lm" >> $MAKEFILE
    echo "" >> $MAKEFILE
done

echo ".PHONY: clean" >> $MAKEFILE
echo "clean:" >> $MAKEFILE
echo "	rm -fr $BINDIR" >> $MAKEFILE
echo "" >> $MAKEFILE

